from django.urls import path
from .views import BoardListCreateView, BoardDetailView

# rename board_id to id!
urlpatterns = [
    path('', BoardListCreateView.as_view(), name='board-list-create'),
    path('<int:board_id>/', BoardDetailView.as_view(), name='board-detail'),
]


# check owners and members ...


# DELETE and MOVE!!!

# auth_app (1/3) ...
# --------
# errors (0/0) - check
# validation, default, required (0/3) ...
# clean coding and documentation (0/2) ...
# English error texts (0/1) ...


# clean coding (1/3) ...


# for copying
# -----------
# errors (0/?) ...
# validation, default, required (0/3) ...
# clean coding and documentation (0/2) ...
# English error texts (0/1) ...
