# Generated by Django 5.1.4 on 2025-05-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_alter_board_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
