# Generated by Django 5.1.4 on 2025-05-10 12:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['title'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this board.', related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(help_text='User who created and owns the board.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(help_text='Title of the board (required, minimum 3 characters).', max_length=255, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters long.')]),
        ),
    ]
