# Generated by Django 5.1.4 on 2025-05-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
